#!/usr/bin/env python3
"""Regenerate cmake/DdxBoostHeaders.cmake, the Boost subset an installed ddx ships.

Three libraries put the variant in a *subdirectory* instead, where widening
cannot reach it, and name it with a macro the closure never records:
MSVC takes preprocessor/control/detail/msvc/while.hpp where
gcc takes control/detail/while.hpp;
MSVC take mpl/aux_/preprocessed/plain where
gcc takes .../gcc.
Those three go in entire, all variants, whichever compiler is asked.

Usage:
    python3 boost_headers.py                 # rewrite the list
    python3 boost_headers.py --check         # exit 1 if the list is stale
    python3 boost_headers.py --cxx clang++   # ask a different compiler

Expected output today: 202 directories, 3234 files.
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INCLUDE = ROOT / "include"
GENERATED = ROOT / "cmake" / "DdxBoostHeaders.cmake"
DEPENDENCIES = ROOT / "cmake" / "DdxDependencies.cmake"
DEPS_DIR = ROOT / ".deps"

# In preference order, when neither --cxx nor $CXX says otherwise.
COMPILERS = ("g++-15", "g++-14", "g++", "clang++")

# Every combination of the two macros ddx's headers branch on.  They agree
# today -- jit/ and cl/ are header types in every build -- and the union costs
# nothing if they ever stop.
VARIANTS = ((), ("-DDDX_HAS_JIT",), ("-DDDX_HAS_OPENCL",),
            ("-DDDX_HAS_JIT", "-DDDX_HAS_OPENCL"))

# Every file, every subdirectory: the libraries whose variant is
# chosen by -- BOOST_COMPILER_CONFIG,
# the BOOST_PP_CONFIG_FLAGS() ladder,
# BOOST_MPL_CFG_COMPILER_DIR
WHOLE = ("boost/config", "boost/mpl", "boost/preprocessor")

VERSION = re.compile(r'set\(DDX_BOOST_VERSION\s+"([^"]+)"')

# util/version.hpp is configured by CMake into the build tree, not checked in;
# the preprocessor needs one, so render it here from the same project() line.
VERSION_TEMPLATE = INCLUDE / "util" / "version.hpp.in"
PROJECT_VERSION = re.compile(r"project\(ddx VERSION (\d+)\.(\d+)\.(\d+)")

BANNER = """\
# Generated by scripts/boost_headers.py against Boost {version}.  Do not edit.
#
# The directories an installed ddx copies out of the fetched Boost, one level
# deep each.  Regenerate after bumping DDX_BOOST_VERSION or after a public
# header names a Boost library it did not before:
#
#     python3 scripts/boost_headers.py
#
# DdxInstall.cmake fails the build if a name here holds no files, so a stale
# list is a stopped build rather than a short install.
set(DDX_BOOST_HEADER_DIRS
{entries})
"""

def pinned_version() -> str:
    """Read DDX_BOOST_VERSION out of the one place that pins it."""
    found = VERSION.search(DEPENDENCIES.read_text())
    if found is None: sys.exit(f"no DDX_BOOST_VERSION in {DEPENDENCIES}")
    return found.group(1)

def pick_compiler() -> str:
    """Choose the compiler to ask: $CXX, else the newest of COMPILERS on PATH."""
    chosen = os.environ.get("CXX") or next((c for c in COMPILERS if shutil.which(c)), None)
    if chosen is None: sys.exit(f"no C++ compiler found; tried $CXX and {', '.join(COMPILERS)}")
    return chosen

def render_version_header(into: Path) -> None:
    """Write util/version.hpp under `into` as CMake's configure_file would."""
    found = PROJECT_VERSION.search((ROOT / "CMakeLists.txt").read_text())
    if found is None: sys.exit(f"no project(ddx VERSION ...) in {ROOT / 'CMakeLists.txt'}")
    major, minor, patch = found.groups()
    fields = {"ddx_VERSION_MAJOR": major, "ddx_VERSION_MINOR": minor,
              "ddx_VERSION_PATCH": patch, "ddx_VERSION": f"{major}.{minor}.{patch}"}
    text = re.sub(r"@(\w+)@", lambda m: fields[m.group(1)], VERSION_TEMPLATE.read_text())
    target = into / VERSION_TEMPLATE.relative_to(INCLUDE).with_suffix("")
    target.parent.mkdir(parents=True)
    target.write_text(text)

def installed_headers() -> list[Path]:
    """Every header DdxInstall.cmake ships, found the same way it finds them."""
    headers = sorted(INCLUDE.rglob("*.hpp"))
    if not headers: sys.exit(f"no headers under {INCLUDE}")
    return headers

def reachable(cxx: str, boost_root: Path, extra: tuple[str, ...]) -> set[Path]:
    """Boost headers the installed headers reach, as paths under boost_root."""
    with tempfile.TemporaryDirectory() as tmp:
        source = Path(tmp) / "installed.cpp"
        source.write_text("".join(f'#include "{h.relative_to(INCLUDE).as_posix()}"\n'
                                  for h in installed_headers()))
        generated = Path(tmp) / "include"
        render_version_header(generated)
        # -M, not -MM: -MM drops everything found through -isystem, which is
        # every Boost header there is.
        done = subprocess.run(
            [cxx, "-std=c++23", "-fno-exceptions", *extra,
             "-I", str(INCLUDE), "-I", str(generated),
             "-isystem", str(boost_root), "-M", str(source)],
            capture_output=True,
            text=True,
            check=False,
        )
    if done.returncode != 0: sys.exit(f"{cxx} could not preprocess ddx's headers:\n{done.stderr}")
    # Makefile syntax: a target, then paths split over backslash-continued lines.
    tokens = done.stdout.replace("\\\n", " ").split()
    return {
        path.relative_to(boost_root)
        for path in (Path(t) for t in tokens)
        if path.is_absolute() and path.is_relative_to(boost_root)
    }

def directories(boost_root: Path, cxx: str) -> list[str]:
    """Collect the directories to ship: every one reached, plus the WHOLE trees."""
    reached: set[Path] = set()
    for extra in VARIANTS:
        reached |= reachable(cxx, boost_root, extra)
    names = {header.parent.as_posix() for header in reached}
    # Named by the files they hold, not by the directories they are: a name that
    # holds none -- mpl/aux_/preprocessed, all variants and no headers -- would
    # install nothing and trip DdxInstall.cmake's own check.
    names |= {
        found.parent.relative_to(boost_root).as_posix()
        for lib in WHOLE
        for found in (boost_root / lib).rglob("*")
        if found.is_file()
    }
    # "boost" sorts before "boost/assert": a prefix is shorter than what extends it.
    return sorted(names)

def render(names: list[str], version: str) -> str:
    """Build the generated CMake as text, so --check compares without writing."""
    return BANNER.format(version=version, entries="\n".join(f"        {n}" for n in names))

def main() -> int:
    """Regenerate the list, or check it, and report what was found."""
    version = pinned_version()
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--boost-root",
        type=Path,
        default=DEPS_DIR / f"boost-{version}",
        help="the directory holding boost/ (default: the fetched, pinned one)",
    )
    parser.add_argument("--cxx", default=None, help="compiler to ask (default: $CXX)")
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the committed list differs, and write nothing",
    )
    args = parser.parse_args()

    boost_root = args.boost_root.resolve()
    if not (boost_root / "boost" / "version.hpp").is_file():
        sys.exit(f"no Boost at {boost_root}: it has no boost/version.hpp")

    cxx = args.cxx or pick_compiler()
    names = directories(boost_root, cxx)
    wanted = render(names, version)

    if args.check:
        if not GENERATED.is_file():
            print(f"{GENERATED} does not exist", file=sys.stderr)
            return 1
        if GENERATED.read_text() != wanted:
            print(
                f"{GENERATED.relative_to(ROOT)} is stale; "
                f"regenerate it with python3 scripts/boost_headers.py",
                file=sys.stderr,
            )
            return 1
        print(f"{GENERATED.relative_to(ROOT)} is current: {len(names)} directories")
        return 0

    GENERATED.write_text(wanted)
    files = sum(1 for n in names for f in (boost_root / n).glob("*") if f.is_file())
    print(
        f"{GENERATED.relative_to(ROOT)}: {len(names)} directories, "
        f"{files} files, asked {cxx} against Boost {version}"
    )
    return 0

if __name__ == "__main__":
    sys.exit(main())
